#!/usr/bin/env python3
"""
PaperCut printer installer for Linux.

Reads a printer config generated by discover.py and adds each printer to CUPS
using driverless IPP Everywhere printing. No proprietary drivers needed.

Usage:
    sudo python3 install.py --config printers.json
    sudo python3 install.py --config printers.json --remove
    sudo python3 install.py --config printers.json --list
    sudo python3 install.py --config printers.json --test
"""

import argparse
import json
import os
import socket
import subprocess
import sys


def load_config(path: str) -> list[dict]:
    if not os.path.exists(path):
        print(f"Config file not found: {path}")
        print("Run discover.py first to generate it:")
        print("  python3 discover.py --pcap capture.pcapng")
        sys.exit(1)
    with open(path) as f:
        return json.load(f)


def ipp_url(p: dict) -> str:
    scheme = "ipps" if p.get("scheme") == "https" else "ipp"
    name = p["name"].replace(" ", "+")
    return f"{scheme}://{p['server']}:{p['port']}/printers/{name}/users/{p['user_id']}/{p['token']}"


def cups_name(p: dict) -> str:
    return p["name"].replace(" ", "-")


def run(cmd: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True)


def check_root() -> None:
    if os.geteuid() != 0:
        print("Error: must run as root (use sudo)")
        sys.exit(1)


def check_cups() -> None:
    if run(["which", "lpadmin"]).returncode != 0:
        print("CUPS not found. Install it first:")
        print("  Ubuntu/Debian : sudo apt install cups")
        print("  Arch          : sudo pacman -S cups")
        print("  Fedora        : sudo dnf install cups")
        print("  Void          : sudo xbps-install cups")
        sys.exit(1)


def check_server(printers: list[dict]) -> None:
    server = printers[0]["server"]
    port = printers[0]["port"]
    print(f"Checking {server}:{port}...", end=" ", flush=True)
    try:
        socket.setdefaulttimeout(3)
        socket.getaddrinfo(server, port)
        print("reachable")
    except socket.gaierror:
        print("UNREACHABLE")
        print("Make sure you are on the correct network.")
        sys.exit(1)


def printer_exists(name: str) -> bool:
    return run(["lpstat", "-p", name]).returncode == 0


def install_printer(p: dict) -> bool:
    name = cups_name(p)
    url = ipp_url(p)
    display = p["name"]
    # -m everywhere = IPP Everywhere driverless driver, handles PDF natively
    result = run(["lpadmin", "-p", name, "-v", url, "-m", "everywhere", "-E",
                  "-D", display])
    if result.returncode != 0:
        print(f"\n  lpadmin error: {result.stderr.strip()}")
        return False
    run(["cupsenable", name])
    run(["cupsaccept", name])
    return True


def remove_printer(p: dict) -> bool:
    return run(["lpadmin", "-x", cups_name(p)]).returncode == 0


def cmd_list(printers: list[dict]) -> None:
    print(f"{'CUPS name':<25} {'IPP URL'}")
    print("-" * 100)
    for p in printers:
        print(f"{cups_name(p):<25} {ipp_url(p)}")


def cmd_test(printers: list[dict]) -> None:
    check_cups()
    check_server(printers)
    print("All checks passed.")


def cmd_install(printers: list[dict]) -> None:
    check_root()
    check_cups()
    check_server(printers)
    print()
    ok = 0
    for p in printers:
        name = cups_name(p)
        exists = printer_exists(name)
        label = "(update)" if exists else "(new)   "
        print(f"  {label} {name}...", end=" ", flush=True)
        if install_printer(p):
            print("done")
            ok += 1
        else:
            print("FAILED")
    print(f"\n{ok}/{len(printers)} printers installed.")
    if ok:
        print("Open any application and print to test.")


def cmd_remove(printers: list[dict]) -> None:
    check_root()
    ok = 0
    for p in printers:
        name = cups_name(p)
        print(f"  Removing {name}...", end=" ", flush=True)
        if remove_printer(p):
            print("removed")
            ok += 1
        else:
            print("not found / skipped")
    print(f"\n{ok} printer(s) removed.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--config", default="printers.json", metavar="FILE",
                        help="printer config from discover.py (default: printers.json)")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--remove", action="store_true", help="remove all printers in config")
    group.add_argument("--list",   action="store_true", help="list printers without installing")
    group.add_argument("--test",   action="store_true", help="test reachability only")
    args = parser.parse_args()

    printers = load_config(args.config)

    if args.list:
        cmd_list(printers)
    elif args.test:
        cmd_test(printers)
    elif args.remove:
        cmd_remove(printers)
    else:
        cmd_install(printers)


if __name__ == "__main__":
    main()
